# name: sync-to-dev
# on:
#   push:
#     branches:
#       - feature
# jobs:
#   push-test:
#     runs-on: ubuntu-latest
#     steps:
#        - name: Checkout code
#          uses: actions/checkout@v2
#          with:
#             fetch-depth: 0
#        - name: Extract latest commit
#          id: extract_commit
#          run: |
#            latest_commit=$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/commits/${GITHUB_REF##*/}" | grep -oP '(?<="sha": ")[^"]*')
#            echo "commit_sha=${latest_commit}" >> GITHUB_OUTPUT
      
#        - name: Rebase 
#          run: |
#           git config --global user.email github-actions@github.com
#           git config --global user.name github-actions
#           BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
#           # echo "Branch name is $BRANCH_NAME!" 
#           git checkout $BRANCH_NAME
#           echo "0"
#           # git rebase --onto origin/main $BRANCH_NAME
#           git rebase origin/main
#           echo "1"
#           # git pull origin main
#           # git config --global pull.rebase true 
#           # git pull --rebase origin main
#           echo "2"
#           git checkout main
#           # git rebase --onto $BRANCH_NAME origin/main
#           git rebase $BRANCH_NAME
#           echo "3"
#           git push origin main
#           echo "4"
