name: sync-to-dev
on:
  push:
    branches:
      - feature1
jobs:
  push-test:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout code
         uses: actions/checkout@v2
       - name: Dump GitHub context
         env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
         run: echo "$GITHUB_CONTEXT"
       - name: Rebase through push
         env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git fetch origin
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          echo "Branch name is $BRANCH_NAME!" 
          git checkout main
          git rebase --onto feature1 main
          git push origin main
          
    
      
