name: sync-to-dev
on:
  push:
    branches:
      - feature
jobs:
  push-test:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout code
         uses: actions/checkout@v2
         with:
            fetch-depth: 0      
       - name: Rebase 
         run: |
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          git checkout feature
          echo "0"
          git rebase --onto origin/main feature
          echo "1"
          # git pull origin main
          # git config --global pull.rebase true 
          # git pull --rebase origin main
          echo "2"
          git checkout main
          git rebase --onto feature origin/main
          # git rebase feature
          echo "3"
          git push origin main
          echo "4"
